

#################################################################
#####################################################################
#configuration HERE
substitutions:
  name: "test_ssr"
  api_pass: "" #your HOME ASSISTANT API
  ota_pass: "" #your Esphome OTA pass
  #modbus
  slave_id: "4" # slave address
  modbus_baud_rate: "9600"
  modbus_stop_bits: "1"
  modbus_data_bits: "8"
  modbus_parity: "NONE"
  modbus_rx_buffer_size: "1500"
  modbus_direction: "BOTH"
  #ethernet
  eth_ip: "192.168.1.102"
  eth_gateway: "192.168.1.1"
  eth_subnet: "255.255.255.0 "
  #webserver login
  user: admin # You must change it for web login
  pass: admin # You must change it for web login
  #I2C address 
  i2c_address_in: "0x20" # You must change it if you changed jumper at I2C_U1 maker
  i2c_address_out: "0x27" # You must change it if you changed jumper at I2C_U2 maker
  i2c_frequency: "400kHz"
#####################################################################
###### MODBUS_MAPS ###### Not yet configuration in this file
# RELAY
# U2-P0  -->> 11
# U2-P1  -->> 12
# U2-P2  -->> 13
# U2-P3  -->> 14
# U2-P4  -->> 15
# U2-P5  -->> 16
# U2-P6  -->> 17
# U2-P7  -->> 18
# U2-P10 -->> 19
# U2-P11 -->> 20
# U2-P12 -->> 21
# U2-P13 -->> 22
# U2-P14 -->> 23
# U2-P15 -->> 24
# U2-P16 -->> 25
# U2-P17 -->> 26

esphome:
  name: "${name}"

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: github://epiclabs-io/esphome-modbus-server@master
    refresh: 60s
    components:
      - modbus_server
    
#ethernet:
#  type: LAN8720
#  mdc_pin: GPIO23
#  mdio_pin: GPIO18
#  clk_mode: GPIO17_OUT
#  phy_addr: 0

  # Optional manual IP

 
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gg Fallback Hotspot"
    password: "v2qDtauPY7kh"
  manual_ip:
    static_ip: ${eth_ip}
    gateway: ${eth_gateway}
    subnet: ${eth_subnet} 
# Enable logging
captive_portal:
  # Optional manual IP

logger:
#  level: VERBOSE
  logs:
    component: ERROR
# Enable Home Assistant API
api:
  encryption:
    key: ${api_pass}

ota:
- platform: esphome
  password: ${ota_pass}
web_server:
  port: 80
  auth:
    username: ${user}
    password: ${pass}
# Example configuration entry for ESP32
i2c:
  sda: 5
  scl: 16
  scan: true
  id: bus_a
  frequency: ${i2c_frequency}
# Example configuration entry
pcf8574:
  - id: 'pcf8574_hub_out_1'  # for output channel 1-16
    i2c_id: bus_a
    address: ${i2c_address_out}
    pcf8575: true
  - id: 'pcf8574_hub_in_1'  # for input channel 1-16
    i2c_id: bus_a
    address: ${i2c_address_in}
    pcf8575: true

# Enable Home Assistant API
uart:
  - id: intmodbus
    tx_pin: 14
    rx_pin: 13
    baud_rate: ${modbus_baud_rate}
    stop_bits: ${modbus_stop_bits}
    data_bits: ${modbus_data_bits}
    parity: ${modbus_parity}
    rx_buffer_size: ${modbus_rx_buffer_size}
    debug:
      direction: ${modbus_direction}

# Individual outputs
#switch:
 # - platform: gpio
  #  name: "light "
  #  pin: GPIO15
   # id: den
switch:
  - platform: gpio
    name: ${name} U2-P00
    id: p0
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 0
      mode: OUTPUT
      inverted: true
  - platform: gpio
    name: ${name} U2-P01
    id: p1
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 1
      mode: OUTPUT
      inverted: true
  - platform: gpio
    name: ${name} U2-P02
    id: p2
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 2
      mode: OUTPUT
      inverted: true
  - platform: gpio
    name: ${name} U2-P03
    id: p3
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 3
      mode: OUTPUT
      inverted: true
  #- platform: gpio
  #  name: ${name} U2-P04
  #  id: p4
  #  pin:
  #    pcf8574: pcf8574_hub_out_1
  #    number: 4
  #   mode: OUTPUT
  #    inverted: true
  #- platform: gpio
  #  name: ${name} U2-P05
  #  id: p5
  #  pin:
  #    pcf8574: pcf8574_hub_out_1
  #    number: 5
  #    mode: OUTPUT
  #    inverted: true
  #- platform: gpio
  #  name: ${name} U2-P06
  #  id: p6
  #  pin:
  #    pcf8574: pcf8574_hub_out_1
  #    number: 6
  #    mode: OUTPUT
  #    inverted: true
  #- platform: gpio
  #  name: ${name} U2-P07
  #  id: p7
  #  pin:
  #    pcf8574: pcf8574_hub_out_1
  #    number: 7
  #    mode: OUTPUT
  #    inverted: true
  - platform: gpio
    name: ${name} U2-P10
    id: p10
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 8
      mode: OUTPUT
      inverted: true
  - platform: gpio
    name: ${name} U2-P11
    id: p11
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 9
      mode: OUTPUT
      inverted: true
  - platform: gpio
    name: ${name} U2-P12
    id: p12
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 10
      mode: OUTPUT
      inverted: true  
  - platform: gpio
    name: ${name} U2-P13
    id: p13
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 11
      mode: OUTPUT
      inverted: true   
  - platform: gpio
    name: ${name} U2-P14
    id: p14
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 12
      mode: OUTPUT
      inverted: true
  - platform: gpio
    name: ${name} U2-P15
    id: p15
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 13
      mode: OUTPUT
      inverted: true
  - platform: gpio
    name: ${name} U2-P16
    id: p16
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 14
      mode: OUTPUT
      inverted: true
  - platform: gpio
    name: ${name} U2-P17
    id: p17
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 15
      mode: OUTPUT
      inverted: true

binary_sensor:
  - platform: gpio
    name: ${name} ETH32-IN0
    id: SW0
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 0
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 250ms      
    on_press:
      then:
        - switch.toggle: p0
  - platform: gpio
    name: ${name} ETH32-IN1
    id: SW1
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 1
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 250ms      
    on_press:
      then:
        - switch.toggle: p1
  - platform: gpio
    name: ${name} ETH32-IN2
    id: SW2
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 2
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 250ms      
    on_press:
      then:
        - switch.toggle: p2
  - platform: gpio
    name: ${name} ETH32-IN3
    id: SW3
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 3
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 250ms      
    on_press:
      then:
        - switch.toggle: p3
  - platform: gpio
    name: ${name} ETH32-IN4
    id: SW4
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 4
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 250ms      
 #   on_press:
 #     then:
 #       - switch.toggle: p4
  - platform: gpio
    name: ${name} ETH32-IN5
    id: SW5
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 5
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 250ms      
 #   on_press:
 #     then:
 #       - switch.toggle: p5
  - platform: gpio
    name: ${name} ETH32-IN6
    id: SW6
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 6
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 250ms      
 #   on_press:
 #     then:
 #       - switch.toggle: p6
  - platform: gpio
    name: ${name} ETH32-IN7
    id: SW7
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 7
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 250ms      
 #   on_press:
 #     then:
 #       - switch.toggle: p7
  - platform: gpio
    name: ${name} ETH32-IN10
    id: SW8
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 8
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 250ms      
    on_press:
      then:
        - switch.toggle: p10
  - platform: gpio
    name: ${name} ETH32-IN11
    id: SW9
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 9
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 250ms      
    on_press:
      then:
        - switch.toggle: p11
  - platform: gpio
    name: ${name} ETH32-IN12
    id: SW10
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 10
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 250ms      
    on_press:
      then:
        - switch.toggle: p12
  - platform: gpio
    name: ${name} ETH32-IN13
    id: SW11
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 11
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 250ms      
    on_press:
      then:
        - switch.toggle: p13
  - platform: gpio
    name: ${name} ETH32-IN14
    id: SW12
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 12
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 250ms      
    on_press:
      then:
        - switch.toggle: p14
  - platform: gpio
    name: ${name} ETH32-IN15
    id: SW13
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 13
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 250ms      
    on_press:
      then:
        - switch.toggle: p15
  - platform: gpio
    name: ${name} ETH32-IN16
    id: SW14
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 14
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 250ms      
    on_press:
      then:
        - switch.toggle: p16
  - platform: gpio
    name: ${name} ETH32-IN17
    id: SW15
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 15
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 250ms      
    on_press:
      then:
        - switch.toggle: p17
#############################
sensor:
  - platform: dht
    pin: GPIO2
    temperature:
      name: "Living Room Temperature"
      id: t_room
    humidity:
      name: "Living Room Humidity"
      id: h_room
    update_interval: 5s
    #sensor:
  - platform: adc   ##POT 47k
    name: "Target temperature"
    pin: GPIO36
    id: t_target
    icon: "mdi:temperature-celsius"
    update_interval: 5s
    attenuation: 11dB
    # Convert potentiometer scale to °C (min=10°C, max=80°C)
    filters:
     - multiply: 0.00095238 # 3.9/4095, for attenuation 11db
    unit_of_measurement: "°C"
    on_value:
      then:
        - lambda: |-
           static float x_last = 0.0;
           if (x<x_last-0.1 || x>x_last+0.1)
           {
            x_last = x;
            auto call = id(pid_climate).make_call();
            call.set_target_temperature(x);
            call.perform();
           }
  - platform: adc
    name: "GPIO39"
    pin: GPIO39
    accuracy_decimals: 3
    update_interval: 20s
    attenuation: 11dB
    icon: "mdi:triangle-wave"
    unit_of_measurement: "%"
    filters:
     - multiply: 0.00095238 # 3.9/4095, for attenuation 11db
  - platform: adc
    name: "GPIO34"
    pin: GPIO34
    accuracy_decimals: 3
    update_interval: 20s
    attenuation: 11dB
    icon: "mdi:triangle-wave"
    unit_of_measurement: "%"
    filters:
     - multiply: 0.00095238 # 3.9/4095, for attenuation 11db
  - platform: adc
    name: "GPIO35"
    pin: GPIO35
    accuracy_decimals: 3
    update_interval: 20s
    attenuation: 11dB
    icon: "mdi:triangle-wave"
    unit_of_measurement: "%"
    filters:
     - multiply: 0.00095238 # 3.9/4095, for attenuation 11db

  - platform: pid
    name: "PID result"
    type: RESULT
    climate_id: pid_climate
################################################
# example for reading pulse of Sine wave, if ac_dimmer not working
#sensor:
 # - platform: pulse_counter
 #   pin: GPIO4
 #   name: "Pulse Counter"    
###############################################
#ZC: GPIO4
#DIM: GPIO15
#Contactor: U2_P10
# Example configuration entry
output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: GPIO33
    zero_cross_pin:
      number: GPIO4
      allow_other_uses: true
      mode:
        input: true
      inverted: yes
    min_power: 0.26
    max_power: 1    
  - platform: ac_dimmer
    id: dimmer2
    gate_pin: GPIO32
    zero_cross_pin:
      number: GPIO4
      allow_other_uses: true
      mode:
        input: true
      inverted: yes
    min_power: 0.26
    max_power: 1  
  - platform: ac_dimmer
    id: dimmer3
    gate_pin: GPIO15
    zero_cross_pin:
      number: GPIO4
      allow_other_uses: true
      mode:
        input: true
      inverted: yes
    min_power: 0.26
    max_power: 1  
#############
#############
light:
  - platform: monochromatic
    output: dimmer2
    name: Dimmerized Light 2
  - platform: monochromatic
    output: dimmer3
    name: Dimmerized Light 3
# Example configuration entry
# The PID controller example.
climate:
  - platform: pid
    id: pid_climate
    name: "PID Climate Controller"
    sensor: t_room
    default_target_temperature: 34°C
    heat_output: dimmer1
    visual:
      min_temperature: 18
      max_temperature: 80
    control_parameters:
      kp: 0.27284
      ki: 0.00218
      kd: 0.00000
      output_averaging_samples: 5      # smooth the output over 5 samples
      derivative_averaging_samples: 5  # smooth the derivative value over 10 samples
    deadband_parameters:
      threshold_high: 0.5°C       # deadband within +/-0.5°C of target_temperature
      threshold_low: -0.5°C
button:
  - platform: template
    name: "PID Climate Autotune"
    on_press:
      - climate.pid.autotune: pid_climate
      - climate.pid.set_control_parameters:
          id: pid_climate
          kp: 0.0
          ki: 0.0
          kd: 0.0



    